export const GET_GROUPS = 'GET_GROUPS';
export const GET_SINGLE_GROUP = 'GET_SINGLE_GROUP';
export const GET_PHOTOS = 'GET_PHOTOS';
export const GET_PHOTOS_FURTHER = 'GET_PHOTOS_FURTHER';
export const FETCH_ERROR = 'FETCH_ERROR';